# Generated by Django 3.2.6 on 2021-09-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
