# Generated by Django 3.2.6 on 2021-09-06 13:38

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('earn', '0002_alter_withdraw_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('firstname', models.CharField(default='', max_length=10)),
                ('lastname', models.CharField(default='', max_length=10)),
                ('age', models.IntegerField(max_length=2)),
                ('gender', models.CharField(max_length=6)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(8)])),
            ],
        ),
    ]
