# Generated by Django 3.2.6 on 2021-09-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earn', '0003_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='age',
            field=models.IntegerField(),
        ),
    ]
