# Generated by Django 3.2.6 on 2021-09-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earn', '0006_rename_id_quiz_id_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('like', models.CharField(max_length=6)),
                ('rate', models.CharField(default='', max_length=100)),
                ('dislike', models.CharField(default='', max_length=100)),
                ('rules', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
