# Generated by Django 3.2.6 on 2021-09-06 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earn', '0007_quiz2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quiz2',
            new_name='Quiz1',
        ),
    ]
