# Generated by Django 3.2.6 on 2021-09-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earn', '0008_rename_quiz2_quiz1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.IntegerField()),
            ],
        ),
    ]
